services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - app_storage:/var/www/storage
      - app_cache:/var/www/bootstrap/cache
    depends_on:
      - db
    expose:
      - '80'

  db:
    image: mariadb:11.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  app_storage:
  app_cache:
  db_data:
